// DEVELOPMENT

### Get all contacts
GET http://localhost:8080/contacts

### Get contact by id
GET http://localhost:8080/contacts/69fb6296b1c1dd4444ae9bac

### Create new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Mario",
  "lastName": "Rossi",
  "email": "mario.rossi@example.com",
  "favoriteColor": "Green",
  "birthday": "1992-03-15"
}

// PRODUCTION

### Get all contacts
GET https://cse341-project1-t3pw.onrender.com/contacts


### Get contact by id
GET https://cse341-project1-t3pw.onrender.com/contacts/69fb6296b1c1dd4444ae9bac